version: "2.2"
services:
  php:
    build: config/docker
    container_name: php
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./:/application
